### PR TITLE
skip scamp when using astrometry.net

### PR DESCRIPTION
**Pull request by saarahha**
This pull request resolves the incompatibility between `a-net` and Scamp. For `a-net` solutions with distortions, important header keywords (A_0_0, ... B_0_0, ...) were being ignored by Scamp. This PR removes the Swarp processor's prerequisite to run Scamp, thus you can run astrometry.net (instead of AutoAstrometry) and skip Scamp, as long as your call to Swarp uses the variable `include_scamp=False`.

### CODE REVIEW

**Comment by robertdstein** [comment]
I think rebase this and if it goes green I'll do a review?

**Review by robertdstein — CHANGES_REQUESTED** [review]
I think my only request is to delete the code rather than comment it out, otherwise looks good!

**Comment by robertdstein** [comment]
( I left a few comments in line)

**Comment by saarahha** [comment]
> ( I left a few comments in line)

I don't see any comments in the files (checked `Files Changed` tab and comments in the current main branch)

**Review by saarahha — COMMENTED** [review]
ah - I didn't know I could approve changes with this interface so I manually made the changes.

**Review by robertdstein — APPROVED** [review]

**Pull request merged**
